spring:
  application:
    name: nacos-cart # 定义当前服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 指定正在运行的Nacos服务器的位置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
dubbo:
  protocol:
    # port设置为-1 表示当前dubbo框架使用的端口自动寻找
    # 使用端口的规则时从20880开始寻找可用端口，+1寻找
    port: -1
    # 设置连接的名称，一般固定为dubbo即可
    name: dubbo
  registry:
    # 指定当前Dubbo服务注册中心的类型和位置
    address: nacos://127.0.0.1:8848
  consumer:
    # 当前项目启动时，是否检查当前项目需要的所有Dubbo服务是否可用
    # 我们设置它为false，表示不检查,以减少启动时出错的情况
    check: false
seata:
  tx-service-group: mall_group # 定义事务的分组,一般以项目为单位,方便与其他项目区分
  service:
    vgroup-mapping:
      mall_group: default # mall_group分组的配置,default会默认配置Seata
    grouplist:
      default: 127.0.0.1:8091 # 配置Seata服务器的地址和端口号
